# -*- coding: utf-8 -*-
"""Primera pre entrega - Macchia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMSfJwiARqQuHQWuzV0f3JGisvCe42aj
"""
'''
from ast import NotIn
#from google.colab import drive
#drive.mount('/drive/')
ruta = '/drive/MyDrive/CoderHouse/Python/SegundaPreEntrega/paquete1/'
#ruta_archivo = ruta + "/diccionario.txt"
f = open("diccionario.txt", "w+")
#f.write("Diccionario de registros vacio\n")
#f.close()

# Creo el diccionario vacío
diccionario = {}

# Función para registrar usuarios
def registro():
    print("\n *** Registrar un nuevo usuario ***\n")
    usr = str(input("Ingrese el nombre de usuario a registrar: ")).lower()
    if usr not in diccionario:  #chequea que ya no haya sido creado
      while True:
          try:
              pwd = int(input("Ingrese la contraseña numérica a registrar: "))
              break
          except ValueError:
              print("\nLa contraseña debe ser numérica \n")
          continue
    else:
        return print("\nEl usuario ya existe \n")
   
    print("\nRegistro completado \n")
    guardar(usr,pwd)
    return

# Función login
def login():
    print("\n *** Login ***\n")
    usuario = str(input("Ingrese su nombre de usuario: ")).upper()
    
    if usuario in diccionario:
        contraseña = int(input("Ingrese su contraseña: "))
        if contraseña == diccionario[usuario]:
           return print(f"\nBienvenido {usuario} al sistema!! \n")
        else:
         return print("\nIngresó una contraseña incorrecta \n")
    else:
        print("\nIngresó un usuario incorrecto \n")


# Función leer
def leer():
    print("\n *** Leer información de usuarios ***\n")
    f = open("diccionario.txt", "r")
    for line in f.readlines():
        print(line)
    f.close()

# Función para guardar los datos, es llamada en la función registro()
def guardar(usr, pwd):
  if usr in diccionario:
    return print("El usuario ya está registrado")
    
  else:

    diccionario.update({usr:pwd})
    f = open("diccionario.txt", "w+")
    for dato in diccionario:
      f.write(f"Usuario: {dato} - Contraseña: {diccionario[dato]}\n")
    f.close()

# Menú de inicio, corre hasta elegir la opción de salir
while True :

    print("\n*** Menú Principal - Primera pre entrega ***\n")
    print("1: Registro de nuevo usuario ")
    print("2: Login ")
    print("3: Leer información de usuarios ")
    print("4: Salir del sistema ")

    opcion = int(input("\n Elija una opción: "))
    if opcion == 1:
        registro()
    elif opcion == 2:
        login()
    elif opcion == 3:
        leer()
    elif opcion == 4:
        print("\nUsted salió correctamente del sistema. Gracias")
        break
    else:
        print("\nElija una opción válida (entre 1 y 4)")
'''